deployment:
  tasks:
    - export DEPLOYPATH=/home3/carnebv0/public_html/
    - ls
    - echo $OSTYPE
    - npm i npm@latest -g
    - npm i -g @angular/cli
    - npm i
    - ng build --prod
    - /bin/cp -R dist $DEPLOYPATH
    - ./run-deploy.sh
