language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

script:
  - npm i -g @angular/cli
  - npm i
  - ng build --prod

after_success:
  - set -e
  - ftp -n $FTP_HOST
  - user $FTP_USER password $FTP_PASS
