language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

script:
  - npm i -g @angular/cli
  - npm i
  - ng build --prod

after_success:
  - set -e
  - ftp -n ftp.carmenscholte.com
  - user admin@carmenscholte.com
